#!/bin/sh

######################################################################
#
# unhide - open hidden file right there
#
# USAGE: unhide <file> ...
#
# Written by fujis (ppdx999@gmail) on 2024-04-10
#
# This is a public-domain software (CC0). It means that all of the
# people can use this for any purposes with no restrictions at all.
# By the way, We are fed up with the side effects which are brought
# about by the major licenses.
#
# The latest version is distributed at the following page.
# https://github.com/ppdx999/unhide
#
######################################################################

# === Initialize shell environment ===================================
set -u
umask 0022
export LC_ALL=C
export PATH="$(command -p getconf PATH 2>/dev/null)${PATH+:}${PATH-}"
case $PATH in :*) PATH=${PATH#?};; esac
export UNIX_STD=2003  # to make HP-UX conform to POSIX

# === Help message ===================================================
case "$1" in
  -h|--help)
    echo "usage: unhide <file> ..."
    exit 1
  ;;
esac

# === Main routine ===================================================
for file in "$@"
do
  dir=$(dirname "$file")
  base=$(basename "$file")
  new=$(echo "$base" | sed 's/^\.//')

  [ "$base" != "$new" ] && mv "$file" "$dir/$new"
done
